baseURL = "/"
languageCode = "en-us"
title = "oburejin"
theme = "o2"
# theme = "terminal"

[languages]
  [languages.en]
    title = "oburejin"
    subtitle = "A blog about this"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "oburejin"
      logoHomeLink = "/"
